sync:
  defaults:
    mode: "two-way-resolved"
    ignore:
      paths:
        # /var/www/html/var does not need to sync in TYPO3
        - "/var"
        - "/storage"
        #- "/.ddev"
    symlink:
      mode: "portable"
